name: xchanming-version
description: "Action to get the xchanming version that is matching the current branch. Returns a fallback if no matching branch is found."

inputs:
  fallback:
    description: The fallback that is returned if there's no matching branch
    default: trunk
    required: false

outputs:
  xchanming-version:
    description: The matching xchanming version or fallback
    value: ${{ steps.get-version.outputs.xchanming-version }}

runs:
  using: "composite"
  steps:
    - name: Get xchanming version
      id: get-version
      shell: bash
      run: |
        if [[ -n "${{ github.head_ref }}" ]]; then
          ref="refs/heads/${{ github.head_ref }}"
        else
          ref="${{ github.ref }}"
        fi

        echo "Local ref: $ref"

        remote_ref=$(git ls-remote --heads "https://github.com/xchanming/xchanming" "$ref" | cut -f 2)
        if [[ -n "$remote_ref" ]]; then
          version="${remote_ref#"refs/heads/"}"
        else
          remote_ref=$(git ls-remote --heads "https://github.com/xchanming/xchanming" refs/heads/${{ github.base_ref }} | cut -f 2)
          if [[ -n "$remote_ref" ]]; then
            version="${remote_ref#"refs/heads/"}"
          else
            echo "No matching branch found, using fallback"
            version="${{ inputs.fallback }}"
          fi
        fi

        echo "Matching xchanming version: $version"

        echo "xchanming-version=$version" >> "$GITHUB_OUTPUT"