name: ESLint
on:
  workflow_call:
    inputs:
        extensionName:
          description: 'Your extension name'
          required: true
          type: string
        cicadaVersion:
          description: |
            With the default `.auto`, the workflow tries to find a cicada version using the cicada-version action.

            For example, if the current ref is next-1234, it will try to find the ref next-1234 in xchanming/cicada. If there's no matching ref, it will use cicadaVersionFallback
          required: false
          type: string
          default: '.auto'
        cicadaVersionFallback:
          required: false
          type: string
          default: trunk

jobs:
  run:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: xchanming/github-actions/cicada-version@main
        with:
          fallback: ${{ inputs.cicadaVersionFallback }}
        id: version
        if: ${{ inputs.cicadaVersion == '.auto' }}
      - name: Clone Cicada
        uses: actions/checkout@v4
        with:
          repository: xchanming/cicada
          ref: ${{ steps.version.outputs.cicada-version || inputs.cicadaVersion }}

      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install admin deps
        shell: bash
        working-directory: src/Administration/Resources/app/administration
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Install Plugin Dependencies
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run ESLint
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run lint