name: ESLint
on:
  workflow_call:
    inputs:
        extensionName:
          description: 'Your extension name'
          required: true
          type: string
        xchanmingVersion:
          description: |
            With the default `.auto`, the workflow tries to find a xchanming version using the xchanming-version action.

            For example, if the current ref is next-1234, it will try to find the ref next-1234 in xchanming/xchanming. If there's no matching ref, it will use xchanmingVersionFallback
          required: false
          type: string
          default: '.auto'
        xchanmingVersionFallback:
          required: false
          type: string
          default: trunk

jobs:
  run:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: xchanming/github-actions/xchanming-version@main
        with:
          fallback: ${{ inputs.xchanmingVersionFallback }}
        id: version
        if: ${{ inputs.xchanmingVersion == '.auto' }}
      - name: Clone XChanMing
        uses: actions/checkout@v4
        with:
          repository: xchanming/xchanming
          ref: ${{ steps.version.outputs.xchanming-version || inputs.xchanmingVersion }}

      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install admin deps
        shell: bash
        working-directory: src/Administration/Resources/app/administration
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Install Plugin Dependencies
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run ESLint
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run lint